apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: maintenance
    secureJsonData:
      password: maintenance
    jsonData:
      database: maintenance
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
